services:
  - type: web
    name: led-control-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: WS_PORT
        value: 8081
    healthCheckPath: /api/stats
